package sp.com.mvpdemo.greendao.auto;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sp.com.mvpdemo.modle.Keyword;

import sp.com.mvpdemo.greendao.auto.KeywordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig keywordDaoConfig;

    private final KeywordDao keywordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        keywordDaoConfig = daoConfigMap.get(KeywordDao.class).clone();
        keywordDaoConfig.initIdentityScope(type);

        keywordDao = new KeywordDao(keywordDaoConfig, this);

        registerDao(Keyword.class, keywordDao);
    }
    
    public void clear() {
        keywordDaoConfig.clearIdentityScope();
    }

    public KeywordDao getKeywordDao() {
        return keywordDao;
    }

}
